name: 'Git Rewrite Commits'
description: 'AI-powered git commit message rewriter using OpenAI or DeepSeek'
author: 'Fatih Kadir Akın'
inputs:
  provider:
    description: 'AI Provider (openai, deepseek)'
    required: false
    default: 'openai'
  api_key:
    description: 'API Key (OPENAI_API_KEY or DEEPSEEK_API_KEY)'
    required: true
  model:
    description: 'AI Model to use'
    required: false
  max_commits:
    description: 'Number of commits to process'
    required: false
  branch:
    description: 'Branch to rewrite'
    required: false
  template:
    description: 'Custom commit template'
    required: false
  language:
    description: 'Language code (en, zh, es, etc.)'
    required: false
    default: 'en'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install git-rewrite-commits
      run: pip install git-rewrite-commits
      shell: bash

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Run Rewrite
      run: |
        ARGS="--skip-remote-consent --quiet"
        
        if [ -n "${{ inputs.max_commits }}" ]; then ARGS="$ARGS --max-commits ${{ inputs.max_commits }}"; fi
        if [ -n "${{ inputs.model }}" ]; then ARGS="$ARGS --model ${{ inputs.model }}"; fi
        if [ -n "${{ inputs.branch }}" ]; then ARGS="$ARGS --branch ${{ inputs.branch }}"; fi
        if [ -n "${{ inputs.template }}" ]; then ARGS="$ARGS --template '${{ inputs.template }}'"; fi
        if [ -n "${{ inputs.language }}" ]; then ARGS="$ARGS --language ${{ inputs.language }}"; fi
        
        export OPENAI_API_KEY="${{ inputs.api_key }}"
        export DEEPSEEK_API_KEY="${{ inputs.api_key }}"
        
        git-rewrite-commits --provider ${{ inputs.provider }} $ARGS
      shell: bash
branding:
  icon: 'git-commit'
  color: 'blue'
